webtalk_init -webtalk_dir C:/Users/jp17033/OneDrive - University of Bristol/Documents/GitHub/digi-cmdproc-interim/Vivado/190302_digi_cmd_interim_01.sim/sim_1/behav/xsim/xsim.dir/tb_cmdProc_interim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  6 12:39:19 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210985181_175113628_210671967_605" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "28293796-c6fb-4742-9c2a-20d63c995bd6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "39fbb74f0afe4409b2dcdca60c3a32ca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "32" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "475 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "30 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "466" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "199" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "132740_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2202020413 -regid "210985181_175113628_210671967_605" -xml C:/Users/jp17033/OneDrive - University of Bristol/Documents/GitHub/digi-cmdproc-interim/Vivado/190302_digi_cmd_interim_01.sim/sim_1/behav/xsim/xsim.dir/tb_cmdProc_interim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jp17033/OneDrive - University of Bristol/Documents/GitHub/digi-cmdproc-interim/Vivado/190302_digi_cmd_interim_01.sim/sim_1/behav/xsim/xsim.dir/tb_cmdProc_interim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jp17033/OneDrive - University of Bristol/Documents/GitHub/digi-cmdproc-interim/Vivado/190302_digi_cmd_interim_01.sim/sim_1/behav/xsim/xsim.dir/tb_cmdProc_interim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
